version: '3.9'

services:
  pwneu.gateway:
    container_name: pwneu.gateway
    depends_on:
      - pwneu.api
    build:
      context: .
      dockerfile: src/Pwneu.Gateway/Dockerfile
    ports:
      - "37100:8080"
      - "37101:8081"
    environment:
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/home/app/.aspnet/https/pwneu.pfx
      - ASPNETCORE_Kestrel__Certificates__Default__Password=${SSL_CERTIFICATE_PASSWORD}
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
    volumes:
      - ./.containers/certs:/home/app/.aspnet/https:ro
    networks:
      - pwneu

  pwneu.api:
    container_name: pwneu.api
    depends_on:
      - pwneu.db
      - pwneu.cache
      - pwneu.dashboard
      - pwneu.mq
    build:
      context: .
      dockerfile: src/Pwneu.Api/Dockerfile
    ports:
      - "37200:8080"
      - "37201:8081"
    environment:
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/home/app/.aspnet/https/pwneu.pfx
      - ASPNETCORE_Kestrel__Certificates__Default__Password=${SSL_CERTIFICATE_PASSWORD}
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://pwneu.dashboard:18889
      - ConnectionStrings__Postgres=${POSTGRES_CONNECTION}
      - MessageBroker__Username=${RABBITMQ_DEFAULT_USER}
      - MessageBroker__Password=${RABBITMQ_DEFAULT_PASS}
      - AppOptions__RequireRegistrationKey=${REQUIRE_REGISTRATION_KEY}
      - AppOptions__InitialAdminPassword=${ADMIN_PASSWORD}
      - JwtOptions__Issuer=${JWT_ISSUER}
      - JwtOptions__Audience=${JWT_AUDIENCE}
      - JwtOptions__SigningKey=${JWT_SIGNING_KEY}
    volumes:
      - ./.containers/certs:/home/app/.aspnet/https:ro
    networks:
      - pwneu

  pwneu.db:
    image: postgres:latest
    container_name: pwneu.db
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - ./.containers/db:/var/lib/postgresql/data
    ports:
      - "37202:5432"
    networks:
      - pwneu

  pwneu.submissions:
    container_name: pwneu.submissions
    depends_on:
      - pwneu.submissions.db
      - pwneu.cache
      - pwneu.dashboard
      - pwneu.mq
    build:
      context: .
      dockerfile: src/Pwneu.Submissions/Dockerfile
    ports:
      - "37300:8080"
      - "37301:8081"
    environment:
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/home/app/.aspnet/https/pwneu.pfx
      - ASPNETCORE_Kestrel__Certificates__Default__Password=${SSL_CERTIFICATE_PASSWORD}
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
      - MessageBroker__Username=${RABBITMQ_DEFAULT_USER}
      - MessageBroker__Password=${RABBITMQ_DEFAULT_PASS}
    volumes:
      - ./.containers/certs:/home/app/.aspnet/https:ro
    networks:
      - pwneu

  pwneu.submissions.db:
    image: postgres:latest
    container_name: pwneu.submissions.db
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - ./.containers/submissions.db:/var/lib/postgresql/data
    ports:
      - "37302:5432"
    networks:
      - pwneu

  pwneu.smtp:
    container_name: pwneu.smtp
    depends_on:
      - pwneu.api
      - pwneu.mq
    build:
      context: .
      dockerfile: src/Pwneu.Smtp/Dockerfile
    ports:
      - "37400:8080"
      - "37401:8081"
    environment:
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/home/app/.aspnet/https/pwneu.pfx
      - ASPNETCORE_Kestrel__Certificates__Default__Password=${SSL_CERTIFICATE_PASSWORD}
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
      - MessageBroker__Username=${RABBITMQ_DEFAULT_USER}
      - MessageBroker__Password=${RABBITMQ_DEFAULT_PASS}
      - SmtpOptions__SenderAddress=${SMTP_SENDER_ADDRESS}
      - SmtpOptions__SenderPassword=${SMTP_SENDER_PASSWORD}
      - SmtpOptions__IsEnabled=${SMTP_IS_ENABLED}
    volumes:
      - ./.containers/certs:/home/app/.aspnet/https:ro
    networks:
      - pwneu

  pwneu.dashboard:
    image: mcr.microsoft.com/dotnet/nightly/aspire-dashboard:latest
    container_name: pwneu.dashboard
    ports:
      - "18888:18888"
    networks:
      - pwneu

  pwneu.cache:
    image: redis:latest
    container_name: pwneu.cache
    ports:
      - "6379:6379"
    networks:
      - pwneu

  pwneu.mq:
    image: rabbitmq:management
    container_name: pwneu.mq
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - ./.containers/queue/data/:/var/lib/rabbitmq
      - ./.containers/queue/log/:/var/log/rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}
    networks:
      - pwneu

networks:
  pwneu:
